# Generated by Django 3.1.1 on 2020-09-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200917_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='tags',
        ),
    ]
