# Generated by Django 3.1.1 on 2020-09-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_link_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='links', to='api.Link'),
        ),
    ]
