# Generated by Django 3.1.1 on 2020-09-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200920_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='listlinks',
            name='list_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.list'),
        ),
        migrations.AlterField(
            model_name='listlinks',
            name='link_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.link'),
        ),
    ]
