# Generated by Django 3.1.1 on 2020-09-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200920_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='links',
        ),
        migrations.AddField(
            model_name='list',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='links', through='api.ListLinks', to='api.Link'),
        ),
    ]
