# Generated by Django 3.1.1 on 2020-09-20 06:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200920_0539'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listlinks',
            managers=[
                ('lists', django.db.models.manager.Manager()),
            ],
        ),
    ]
