# Generated by Django 3.1.1 on 2020-09-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200920_0610'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listlinks',
            managers=[
            ],
        ),
    ]
