# Generated by Django 3.1.1 on 2020-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200920_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='links',
            field=models.ManyToManyField(related_name='links', through='api.ListLinks', to='api.Link'),
        ),
    ]
