# Generated by Django 3.1.1 on 2020-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200920_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='links',
            field=models.ManyToManyField(blank=True, default=None, related_name='links', through='api.ListLinks', to='api.Link'),
        ),
    ]
