# Generated by Django 3.1.1 on 2020-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200920_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='links',
            field=models.ManyToManyField(default=None, related_name='linked', through='api.ListLinks', to='api.Link'),
        ),
    ]
