# Generated by Django 3.1.1 on 2020-09-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('authentication', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'is_favorite': True}, related_name='favorited', to='api.Link'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'is_saved': True}, related_name='saved', to='api.Link'),
        ),
    ]
